/**
 * TAC-T11..T13 — scoreOffense pillar scorer.
 *
 * Stage 5b: tightened to assert exact equality against goldens generated by
 * `scripts/data/build-tactical-goldens.ts` (which runs the real `damage_calc`
 * engine over `fixtures/tactical/2026-05-08__golden-team.json` × `golden-panel.json`).
 *
 * The legacy "no-scoring-inputs" stub path is preserved for shape-only test
 * coverage of the throw-and-skip contract (T13).
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { scoreOffense } from "../../../src/data/tactical/score-offense";
import {
  fixtureToScoringTeam,
  fixtureToScoringPanel,
  type FixtureSet,
} from "../../../src/data/tactical/scoring-team";
import type { ThreatPanel } from "../../../src/schemas/tactical";
import type { UserTeam } from "../../../src/schemas/user-teams";
import { createCalcCache } from "../../../src/data/tactical/calc-cache";

const TEAM = {} as UserTeam;
const PANEL = {} as ThreatPanel;

function loadGolden(name: string): { score: number; evidence: { top: unknown[]; worst: unknown[] } } {
  const p = resolve(process.cwd(), "fixtures/tactical", name);
  return JSON.parse(readFileSync(p, "utf8")) as ReturnType<typeof loadGolden>;
}

interface TeamFixture { sets: FixtureSet[] }
interface PanelFixture { entries: Array<FixtureSet & { weight: number }> }

function loadInputs(): {
  team: ReturnType<typeof fixtureToScoringTeam>;
  panel: ReturnType<typeof fixtureToScoringPanel>;
} {
  const teamFx = JSON.parse(
    readFileSync(resolve("fixtures/tactical/2026-05-08__golden-team.json"), "utf8"),
  ) as TeamFixture;
  const panelFx = JSON.parse(
    readFileSync(resolve("fixtures/tactical/2026-05-08__golden-panel.json"), "utf8"),
  ) as PanelFixture;
  return {
    team: fixtureToScoringTeam(teamFx.sets),
    panel: fixtureToScoringPanel(panelFx.entries),
  };
}

describe("scoreOffense (TAC-T11..T13)", () => {
  it("TAC-T11. golden: real engine loop matches fixtures/tactical/2026-05-08__pillar_offense_golden.json exactly", () => {
    const golden = loadGolden("2026-05-08__pillar_offense_golden.json");
    const { team, panel } = loadInputs();
    const cache = createCalcCache();
    const result = scoreOffense(TEAM, PANEL, cache, {
      scoring_team: team,
      scoring_panel: panel,
    });
    expect(result.pillar).toBe("offense");
    expect(result.score).toBe(golden.score);
    expect(result.evidence).toEqual(golden.evidence);
  });

  it("TAC-T12. KO-chance evidence captures top-3 + worst-2 (5 entries)", () => {
    const { team, panel } = loadInputs();
    const cache = createCalcCache();
    const result = scoreOffense(TEAM, PANEL, cache, {
      scoring_team: team,
      scoring_panel: panel,
    });
    const ev = result.evidence as { top: unknown[]; worst: unknown[] };
    expect(ev.top.length).toBeLessThanOrEqual(3);
    expect(ev.worst.length).toBeLessThanOrEqual(2);
    expect(ev.top.length + ev.worst.length).toBeGreaterThan(0);
  });

  it("TAC-T13. calc-engine throw on a single (our_set, threat_set) pair → skip + continue (stub path)", () => {
    let throwOnce = true;
    const cache = createCalcCache();
    // Stub path: no scoring_team/panel — exercises the deps.calc skip-and-continue contract.
    const result = scoreOffense(TEAM, PANEL, cache, {
      calc: () => {
        if (throwOnce) {
          throwOnce = false;
          throw new Error("simulated engine throw");
        }
        return {} as never;
      },
    });
    // Pillar still produced (skip-and-continue), score in 0..100 range.
    expect(result.score).toBeGreaterThanOrEqual(0);
    expect(result.score).toBeLessThanOrEqual(100);
  });
});
