/**
 * TAC-T14..T15 — scoreDefense pillar.
 *
 * Stage 5b: tightened to assert exact equality against goldens generated by
 * `scripts/data/build-tactical-goldens.ts` (which runs the real `damage_calc`
 * engine).
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { scoreDefense } from "../../../src/data/tactical/score-defense";
import {
  fixtureToScoringTeam,
  fixtureToScoringPanel,
  type FixtureSet,
} from "../../../src/data/tactical/scoring-team";
import type { ThreatPanel } from "../../../src/schemas/tactical";
import type { UserTeam } from "../../../src/schemas/user-teams";
import { createCalcCache } from "../../../src/data/tactical/calc-cache";

const TEAM = {} as UserTeam;
const PANEL = {} as ThreatPanel;

function loadGolden(): { score: number; evidence: { weakest_slot: number; ohko_by_threat: Record<string, number> } } {
  const p = resolve(process.cwd(), "fixtures/tactical/2026-05-08__pillar_defense_golden.json");
  return JSON.parse(readFileSync(p, "utf8")) as ReturnType<typeof loadGolden>;
}

interface TeamFixture { sets: FixtureSet[] }
interface PanelFixture { entries: Array<FixtureSet & { weight: number }> }

function loadInputs(): {
  team: ReturnType<typeof fixtureToScoringTeam>;
  panel: ReturnType<typeof fixtureToScoringPanel>;
} {
  const teamFx = JSON.parse(
    readFileSync(resolve("fixtures/tactical/2026-05-08__golden-team.json"), "utf8"),
  ) as TeamFixture;
  const panelFx = JSON.parse(
    readFileSync(resolve("fixtures/tactical/2026-05-08__golden-panel.json"), "utf8"),
  ) as PanelFixture;
  return {
    team: fixtureToScoringTeam(teamFx.sets),
    panel: fixtureToScoringPanel(panelFx.entries),
  };
}

describe("scoreDefense (TAC-T14..T15)", () => {
  it("TAC-T14. golden: real engine loop matches fixtures/tactical/2026-05-08__pillar_defense_golden.json exactly", () => {
    const golden = loadGolden();
    const { team, panel } = loadInputs();
    const cache = createCalcCache();
    const result = scoreDefense(TEAM, PANEL, cache, {
      scoring_team: team,
      scoring_panel: panel,
    });
    expect(result.pillar).toBe("defense");
    expect(result.score).toBe(golden.score);
    expect(result.evidence).toEqual(golden.evidence);
  });

  it("TAC-T15. weakest-slot evidence reports the slot index in 0..5", () => {
    const { team, panel } = loadInputs();
    const cache = createCalcCache();
    const result = scoreDefense(TEAM, PANEL, cache, {
      scoring_team: team,
      scoring_panel: panel,
    });
    const ev = result.evidence as { weakest_slot: number };
    expect(typeof ev.weakest_slot).toBe("number");
    expect(ev.weakest_slot).toBeGreaterThanOrEqual(0);
    expect(ev.weakest_slot).toBeLessThanOrEqual(5);
  });
});
